Yuko/catalengineer2014/config/routes.rb
Rails.application.routes.draw do
   resources :notes
   resources :groups
   resources :profiles

end

Yuko/catalengineer2014/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def new
    @group = Group.new
  end
  
  def create
    @group =Group.new(group_params)
    if @group.save
      redirect_to @group
    else
      render :new
    end
  end 

  def group_params
    params.require(:group).permit(:title)
  end

  def show
    @group = Group.find(params[:id])
  end

  def index
    @groups = Group.all
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end
 
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
     redirect_to groups_path
  end
end

Yuko/catalengineer2014/app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def new
     @note = Note.new
    end

   def create
    @note = Note.new(note_params)
    if @note.save
     redirect_to @note
    else
     render :new
    end
  end
  
   def note_params
    params.require(:note).permit(:title, :body, :date)
  end

   def show
    @note = Note.find(params[:id])
   end

   def index
    @notes = Note.all
   end
   
   def edit
    @note = Note.find(params[:id])
   end
   
   def update
     @note = Note.find(params[:id])
     if @note.update(note_params)
       redirect_to @note
     else
       render :edit
     end
   end

   def destroy
     @note = Note.find(params[:id])
     @note.destroy
     redirect_to notes_path
   end

end

Yuko/catalengineer2014/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
   @profile  = Profile.new(profile_params)
    if @profile.save
     redirect_to @profile
    else
      render :new
    end
  end

  def profile_params
    params.require(:profile).permit(:title, :body)
  end
  
  def show
   @profile = Profile.find(params[:id])
  end

 def index
   @profiles = Profile.all
 end
  
 def edit
   @profile = Profile.find(params[:id])
 end

 def update
   @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit
    end
 end

  def destroy
   @profile = Profile.find(params[:id])
   @profile.destroy
   redirect_to profiles_path
  end
end

Yuko/catalengineer2014/app/helpers/group_helper.rb
module GroupHelper
end

Yuko/catalengineer2014/app/helpers/groups_helper.rb
module GroupsHelper
end

Yuko/catalengineer2014/app/helpers/profile_helper.rb
module ProfileHelper
end

Yuko/catalengineer2014/app/views/groups/edit.html.erb
<h1>New Group</h1>

<%= form_for(@group) do |f| %>
  <h3><%= f.label :name %></h3>
  <%= f.text_field :title, class: "form-control"%>

  <br>
  <%= f.submit "更新" %>
<% end %>

Yuko/catalengineer2014/app/views/groups/index.html.erb
<h1>Listing Groups</h1>

<table>
  <thread> 
    <tr>
     <th>name</th>
    </tr>
  </thead>

<tbody>
  <% @groups.each do |group| %>
   <tr>
    <td><%= group.title %></td>
    <td><%= link_to 'Show', group_path(group.id) %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data:{ confirm:'本当に削除していいですか？'} %></td>
   </tr>
  <%end%>
</tbody>
</table>

<%= link_to 'New Group', new_group_path %>

<p>
Signed in as yfujimoto210@gmail.com. 
<%= link_to 'Sign out', 'http://www.gmail.com/' %>
</p> 

Yuko/catalengineer2014/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= form_for(@group) do |f| %>
   <h3><%= f.label :name  %></h3>
   <%= f.text_field :title, class: "form-control"%>
<br>
<br>
   <%= f.submit "Create Group" %>

<br>
<br>
<%= link_to 'Back', groups_path %>
<br>
Signed in as yfujimoto210@gmail.com. 
<%= link_to 'Sign out', 'http://www.gmail.com/' %>

<% end %>

Yuko/catalengineer2014/app/views/groups/show.html.erb
Group was successfully created.
<br>

<b>Name:</b>
<%= @group.title %>
<br>
<br>
<%= link_to 'Edit', edit_group_path %> | <%= link_to 'Back', new_group_path %>
<br>
<p>
Signed in as yfujimoto210@gmail.com.
<%= link_to 'Sign out', 'http://www.gmail.com/' %>
</p>

Yuko/catalengineer2014/app/views/notes/edit.html.erb
<h1>New Note</h1>

<%= form_for(@note) do |f| %>
  <h3><%= f.label :date %></h3>
  <%# DateTime.now.strftime('%Y-%m-%d') %>
  <%= f.date_select :date %>

  <h3><%= f.label :title %></h3>
  <%= f.text_field :title, class: "form-control"%>

  <h3><%= f.label :body %></h3>
  <%= f.text_area :body %>

  <br>
  <%= f.submit "更新" %>
<% end %>

Yuko/catalengineer2014/app/views/notes/group.html.erb
<h1>New group</h1>

<%= form_for(@note) do |f| %>
  <h3><%= f.label :name %></h3>
  <%= f.text_field :name, class: "form-control"%>

  <br>
  <%= f.submit "作成" %>
<% end %>

Yuko/catalengineer2014/app/views/notes/index.html.erb
<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>date</th>
      <th>title</th>
      <th>body</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
     <tr>
      <td><%= note.id %></td>
      <td><%= note.date.strftime('%Y-%m-%d') %></td>
      <td><%= note.title %></td>
      <td><%= note.body.html_safe %></td>
      <td><%= link_to 'Show', note_path(note.id) %></td>
      <td><%= link_to 'Edit', edit_note_path(note) %></td>
      <td><%= link_to 'Destroy', note, method: :delete, data:{ confirm:'本当に削除していいですか？'} %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_note_path %>

Yuko/catalengineer2014/app/views/notes/new.html.erb
 <h1>New Note</h1>
 
 <%= form_for(@note) do |f| %>
    <h3><%= f.label :date %></h3>
    <%= f.date_select :date %>


    <h3><%= f.label :title %></h3>
    <%= f.text_field :title, class: "form-control"%>

    <h3><%= f.label :body %></h3>
    <%= f.text_area :body %>

    <br>
    <%= f.submit "作成" %>
 <% end %>