sachiko/catalengineer2014/config/routes.rb
Rails.application.routes.draw do
 resources :groups
 resources :notes
 resources :profiles 

end

sachiko/catalengineer2014/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

 def destroy
  @group = Group.find(params[:id])
  @group.destroy
  redirect_to groups_path
 end

 def update
  @group = Group.find(params[:id])
  if @group.update(group_params)
   redirect_to @group
  else
   render :edit
  end
 end

 def edit
  @group = Group.find(params[:id])
 end

 def index
  @groups = Group.all
 end

 def show
  @group = Group.find(params[:id])
 end

 def new
  @group = Group.new
 end

 def create
  @group = Group.new(group_params)
  if @group.save
   redirect_to @group
  else
   render :new
  end
 end

 def group_params
  params.require(:group).permit(:name)
 end

end

sachiko/catalengineer2014/app/controllers/notes_controller.rb
class NotesController < ApplicationController

 def destroy
  @note = Note.find(params[:id])
  @note.destroy
  redirect_to notes_path
 end

 def update
  @note = Note.find(params[:id])
  if @note.update(note_params)
   redirect_to @note
  else
   render :edit
  end
 end

 def edit
  @note = Note.find(params[:id])
 end

 def index
  @notes = Note.all
 end

 def show
  @note = Note.find(params[:id])
 end

 def new
  @note = Note.new
 end

 def create
  @note = Note.new(note_params)
  if @note.save
   redirect_to @note
  else
   render :new
  end
 end

 def note_params
  params.require(:note).permit(:title, :body, :date)
 end

end

sachiko/catalengineer2014/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

 def destroy
  @profile = Profile.find(params[:id])
  @profile.destroy
  redirect_to profiles_path
 end

 def update
  @profile = Profile.find(params[:id])
  if @profile.update(profile_params)
   redirect_to @profile
  else
   render :edit
  end
 end

 def edit
  @profile = Profile.find(params[:id])
 end

 def index
  @profiles = Profile.all
 end

 def show
  @profile = Profile.find(params[:id])
 end

 def new
  @profile = Profile.new
 end

 def create
  @profile = Profile.new(profile_params)
  if @profile.save
   redirect_to @profile
  else
   render :new
  end
 end

 def profile_params
  params.require(:profile).permit(:name, :avatar)
 end

end

sachiko/catalengineer2014/app/views/groups/index.html.erb
<h1>Listing Groups</h1>
<table>
<thead>
<tr>
 <th>Name</th>
</tr>
</thead>

<tbody>
 <% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td> 
    <td><%= link_to 'Destroy', group, method: :delete, data:{ confirm:'本当に削除していいですか？'} %></td>
  </tr>
  </tr>
 <% end %>
</tbody>
</table>

<%= link_to 'New Group', new_group_path %>

sachiko/catalengineer2014/app/views/groups/new.html.erb
<h1>New group</h1>

<%= form_for(@group) do |f| %>
 <h3><%= f.label :name %></h3>
 <%= f.text_field :name, class: "form-control"%>

 <br>
 <%= f.submit "Create Group" %>

 <br>
 <a href="./">Back</a>

<% end %>

sachiko/catalengineer2014/app/views/groups/show.html.erb
<h5>Group was successfully created.</h5>
<h5>Group was successfully created.</h5>

<h3>Name:
<%= @group.name %>
</h3>

<BR>

<a href="./new">Edit</a> | <a href="./">Back</a>

sachiko/catalengineer2014/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalengineer2014</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sachiko/catalengineer2014/app/views/notes/edit.html.erb
<h1>New Note</h1>

<%= form_for(@note) do |f| %>
  <h3><%= f.label :date %></h3>
  <%# DateTime.now.strftime('%Y-%m-%d') %>
  <%= f.date_select :date %>

  <h3><%= f.label :title %></h3>
  <%= f.text_field :title, class: "form-control"%>

  <h3><%= f.label :body %></h3>
  <%= f.text_area :body %>

  <br>
  <%= f.submit "更新" %>
<% end %>

sachiko/catalengineer2014/app/views/notes/index.html.erb
<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>date</th>
      <th>title</th>
      <th>body</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.id %></td>
        <td><%= note.date.strftime('%Y-%m-%d') %></td>
        <td><%= note.title %></td>
        <td><%= note.body.html_safe %></td>
        <td><%= link_to 'Show', note_path(note.id) %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data:{ confirm:'本当に削除していいですか？'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_note_path %>

sachiko/catalengineer2014/app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_for(@note) do |f| %>
 <h3><%= f.label :date %></h3>
 <%# DateTime.now.strftime('%y-%m-%d') %>
 <%= f.date_select :date %>

 <h3><%= f.label :title %></h3>
 <%= f.text_field :title, class: "form-control"%>

 <h3><%= f.label :body %></h3>
 <%= f.text_area :body %>

 <br>
 <%= f.submit "作成" %>
<% end %>

sachiko/catalengineer2014/app/views/notes/show.html.erb
<h3>Title</h3>
<%= @note.title %>

<h3>Data</h3>
<%= @note.date.strftime('%Y-%m-%d') %>

<h3>Body</h3>
<%= @note.body.html_safe %>

<br>

sachiko/catalengineer2014/app/views/profiles/edit.html.erb
<h1>New profile</h1>

<%= form_for(@profile) do |f| %>
 <h3><%= f.label :name %></h3>
 <%= f.text_field :name, class: "form-control"%>

 <h3><%= f.label :avatar %></h3>
 <%= f.text_field :avatar, class: "form-control"%>

 
 <br>
 <%= f.submit "更新" %>
<% end %>

sachiko/catalengineer2014/app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>
<table>
<thead>
<tr>
 <th>Name</th>
 <th>Avatar</th>
</tr>
</thead>

<tbody>
 <% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.name %></td>
    <td><%= profile.avatar %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td> 
    <td><%= link_to 'Destroy', profile, method: :delete, data:{ confirm:'本当に削除していいですか？'} %></td>
  </tr>
 <% end %>
</tbody>
</table>

<%= link_to 'New Profile', new_profile_path %>

sachiko/catalengineer2014/app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= form_for(@profile) do |f| %>
 <h3><%= f.label :name %></h3>
 <%= f.text_field :name, class: "form-control"%>

 <h3><%= f.label :avatar %></h3>
 <%= f.text_field :avatar, class: "form-control"%>

 <br>
 <%= f.submit "Create Profile" %>

 <br>
 <a href="./">Back</a>

<% end %>

sachiko/catalengineer2014/app/views/profiles/show.html.erb
<h5>Profile was successfully created.</h5>
<h5>Profile was successfully created.</h5>

<h3>Name:
<%= @profile.name %>
</h3>

<h3>Avatar:
<%= @profile.avatar %>
</h3>


<BR>

<a href="./new">Edit</a> | <a href="./">Back</a>