Saki/catalengineer2014/config/routes.rb
Rails.application.routes.draw do
 resources :profiles	 

end

Saki/catalengineer2014/app/models/group.rb
class Group < ActiveRecord::Base
end

Saki/catalengineer2014/app/models/note.rb
class Note < ActiveRecord::Base
end

Saki/catalengineer2014/app/models/profile.rb
class Profile < ActiveRecord::Base
end

Saki/catalengineer2014/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Saki/catalengineer2014/app/controllers/group_controller.rb
class GroupController < ApplicationController 
 def new
   @note = Group.new
 end
end

Saki/catalengineer2014/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

 def show
  @group = Group.find(params[:id])
 end

 def new
  @group = Group.new
 end
 
 def create
  @group = Group.new(group_params)
  if @group.save
    redirect_to @group
  else
    render :new
  end
 end

 def group_params
   params.require(:group).permit(:name)
 end

 def index
   @groups = Group.all
 end

end

Saki/catalengineer2014/app/controllers/notes_controller.rb
class NotesController < ApplicationController
 def index
  @notes = Note.all
 end

def show
    @note = Note.find(params[:id])
  end

 def new
  @note = Note.new
 end


  def create
    @note = Note.new(note_params)
    if @note.save 
      redirect_to @note
    else
      render :new
    end
  end

  def note_params
    params.require(:note).permit(:title, :body, :date)
  end

  def show
    @note = Note.find(params[:id])
  end

end

Saki/catalengineer2014/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 def index
   @profile = Profile.all
 end

 def show
   @profile = Profile.find(params[:id])
 end

 def new
   @profile = Profile.new
 end

 def create 
   @profile = Profile.new(profile_params)
   if @profile.save
     redirect_to @profile
   else 
    render :new
   end
 end

 def profile_params 
   params.require(:profile).permit(:Name, :Avatar)
 end


end

Saki/catalengineer2014/app/helpers/application_helper.rb
module ApplicationHelper
end

Saki/catalengineer2014/app/helpers/notes_helper.rb
module NotesHelper
end

Saki/catalengineer2014/app/helpers/profiles_helper.rb
module ProfilesHelper
end

Saki/catalengineer2014/app/views/groups/index.html.erb
<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.id %></td>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group_path(group.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_group_path %>

Saki/catalengineer2014/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= form_for(@group) do |f| %>
 <%= f.label :Name %>
 <br>
 <%= f.text_field :name %>

 <br>
 <h3><%= f.submit "Create Group" %></h3>

<% end %>

Saki/catalengineer2014/app/views/groups/show.html.erb
<h3>Name</h3>
<%= @group.name %>

<br>

Saki/catalengineer2014/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalengineer2014</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Saki/catalengineer2014/app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<table>
 <thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Avatar</th>
    <th></th>
  </tr>
 </thead>

 <tbody>
   <% @profile.each do |profile| %>
     <tr>
       <td><%= profile.id %></td>
       <td><%= profile.Name %></td>
       <td><%= profile.Avatar %></td>
       <td><%= link_to 'Show', profile_path(profile.id) %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<%= link_to 'New', new_profile_path %>

Saki/catalengineer2014/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= form_for(@profile) do |f| %>
 <%= f.label :Name %>
 <br>
 <%= f.text_field :Name %>

<br>

 <%= f.label :Avatar %>
 <br>
 <%= f.text_field :Avatar %>


 <br>
 <%= f.submit "Create Profile" %>
<% end %>

Saki/catalengineer2014/app/views/profiles/show.html.erb
<h3>Name</h3>
<%= @profile.Name %>

<h3>Avatar</h3>
<%= @profile.Avatar %>

<br>